# Generated by Django 4.1 on 2024-04-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0002_palikageometry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='palikageometry',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='palikageometry',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
