# Generated by Django 4.1 on 2024-04-11 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geospatial', '0003_palikageometry_district_palikageometry_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palikageometry',
            old_name='palika_name',
            new_name='bbox',
        ),
        migrations.RenameField(
            model_name='palikageometry',
            old_name='palikaupload',
            new_name='palika',
        ),
        migrations.RenameField(
            model_name='palikaupload',
            old_name='data_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='palikaupload',
            old_name='upload_date',
            new_name='uploaded_date',
        ),
        migrations.RemoveField(
            model_name='palikageometry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='palikageometry',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='palikageometry',
            name='user',
        ),
        migrations.AddField(
            model_name='palikageometry',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palikageometry',
            name='attr_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palikaupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='palikaupload',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='palikaupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='palikaupload',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='GeoSpatialData',
        ),
    ]
