# Generated by Django 4.1 on 2024-04-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0004_rename_palika_name_palikageometry_bbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palikageometry',
            name='state',
        ),
    ]
