# Generated by Django 4.1 on 2024-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0005_remove_palikageometry_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='palikageometry',
            name='ward_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
