# Generated by Django 4.1 on 2024-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0006_palikageometry_ward_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palikageometry',
            name='ward_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
