# Generated by Django 4.1 on 2024-04-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0008_weatherforecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherforecast',
            old_name='precipitation_probability',
            new_name='relative_humidity_2m',
        ),
    ]
